mzmatch.ipeak.sort.MetAssign <- function(JHeapSize=1425,i=NULL, o=NULL, basepeaks=NULL, ppm=NULL, p1=NULL, p0=NULL, alpha=NULL, alpha0=NULL, alpha1=NULL, numDraws=NULL, burnIn=NULL, databases=NULL, adducts=NULL, minDistributionValue=NULL, maxValues=NULL, rho=NULL, retentionTimeSD=NULL, retentionTimePredSD=NULL, identificationPeaks=NULL, filterPPM=NULL, rtClustering=NULL, seed=NULL, debug=NULL, debugOut=NULL, dbIdentOut=NULL, test=NULL, h=NULL, v=NULL)
{
	version.1 <- get("version.1",envir=.GlobalEnv)
	## define the java runtime parameters
	java <- "java -da -dsa -Xmn1g -Xss228k -XX:+UseParallelGC -XX:ParallelGCThreads=10"
	## locate the mzmatch.jar file (it's included in the peakmlR package)
	## JHeapSize - define amount of RAM availiable for java VM
	JHeapSize <- paste(JHeapSize,"m",sep="")
	java <- paste(java," -Xms",JHeapSize," -Xmx",JHeapSize," -cp",sep="")
	if (version.1==TRUE)
	{
		stop ("This tool can't be used with mzmatch version belw 2.0")
	} else
	{
		mzmatch <- paste(java, " ", find.package("mzmatch.R"), "/java/mzmatch_2.0.jar", sep="")
	}

	## setup the tool
	tool <- paste(mzmatch, "mzmatch.ipeak.sort.MetAssign")
		if (!is.null(i))
		tool <- paste(tool, "-i", i)
	if (!is.null(o))
		tool <- paste(tool, "-o", o)
	if (!is.null(basepeaks))
		tool <- paste(tool, "-basepeaks", basepeaks)
	if (!is.null(ppm))
		tool <- paste(tool, "-ppm", ppm)
	if (!is.null(p1))
		tool <- paste(tool, "-p1", p1)
	if (!is.null(p0))
		tool <- paste(tool, "-p0", p0)
	if (!is.null(alpha))
		tool <- paste(tool, "-alpha", alpha)
	if (!is.null(alpha0))
		tool <- paste(tool, "-alpha0", alpha0)
	if (!is.null(alpha1))
		tool <- paste(tool, "-alpha1", alpha1)
	if (!is.null(numDraws))
		tool <- paste(tool, "-numDraws", numDraws)
	if (!is.null(burnIn))
		tool <- paste(tool, "-burnIn", burnIn)
	if (!is.null(databases))
		tool <- paste(tool, "-databases", databases)
	if (!is.null(adducts))
		tool <- paste(tool, "-adducts", adducts)
	if (!is.null(minDistributionValue))
		tool <- paste(tool, "-minDistributionValue", minDistributionValue)
	if (!is.null(maxValues))
		tool <- paste(tool, "-maxValues", maxValues)
	if (!is.null(rho))
		tool <- paste(tool, "-rho", rho)
	if (!is.null(retentionTimeSD))
		tool <- paste(tool, "-retentionTimeSD", retentionTimeSD)
	if (!is.null(retentionTimePredSD))
		tool <- paste(tool, "-retentionTimePredSD", retentionTimePredSD)
	if (!is.null(identificationPeaks))
		tool <- paste(tool, "-identificationPeaks", identificationPeaks)
	if (!is.null(filterPPM))
		tool <- paste(tool, "-filterPPM", filterPPM)
	if (!is.null(rtClustering))
		tool <- paste(tool, "-rtClustering", rtClustering)
	if (!is.null(seed))
		tool <- paste(tool, "-seed", seed)
	if (!is.null(debug))
		tool <- paste(tool, "-debug", debug)
	if (!is.null(debugOut))
		tool <- paste(tool, "-debugOut", debugOut)
	if (!is.null(dbIdentOut))
		tool <- paste(tool, "-dbIdentOut", dbIdentOut)
	if (!is.null(test))
		tool <- paste(tool, "-test", test)
	if (!is.null(h) && h==T)
		tool <- paste(tool, "-h")
	if (!is.null(v) && v==T)
		tool <- paste(tool, "-v")

	system(tool)
}
